### ISSUE TITLE
adjust-timestamp fails using  :day-of-week offset

### ISSUE THREAD

**Issue by samuel-jimenez** [dlowe-net/local-time#102]
`(adjust-timestamp (encode-timestamp 0 0 0 0 1 11 2020) (offset :day-of-week :sunday))` returns `@2020-10-25T00:00:00.000000Z`.

`(timestamp-day-of-week (encode-timestamp 0 0 0 0 1 11 2020))` returns `0`

**Comment by mmontone** [comment]
`(timestamp-day-of-week (encode-timestamp 0 0 0 0 1 11 2020)) returns 0` 

That's Sunday, and weekday is 0, so what is the problem?

**Comment by mmontone** [comment]
`(adjust-timestamp (encode-timestamp 0 0 0 0 1 11 2020) (offset :day-of-week :sunday)) ` returns
`@2020-11-08T00:00:00.000000Z`, which is the previous Sunday, so that's correct too.

**Comment by mmontone** [comment]
> `(timestamp-day-of-week (encode-timestamp 0 0 0 0 1 11 2020)) returns 0`
> 
> That's Sunday, and weekday is 0, so what is the problem?

My bad, it is a Wednesday, so that's a bug.

**Comment by mmontone** [comment]
> `(adjust-timestamp (encode-timestamp 0 0 0 0 1 11 2020) (offset :day-of-week :sunday))` returns `@2020-10-25T00:00:00.000000Z`.

adjust-timestamp is supposed to give the previous Sunday, so that's correct too

**Comment by dlowe-net** [comment]
Yeah, this is unintuitive but it's working as intended, I think.
