### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [dlowe-net/local-time#104]
Building with SBCL 2.1.0.29-a1ce59262 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id da01c15ab72b3dad38530f569aa096b01966b20c

*cl-postgres+local-time* fails to build because of a failure in  _local-time_.

*local-time* fails to build with the following error:

```
; caught WARNING:
;   Derived type of (TIMEZONE-SUBZONES TIMEZONE) is SIMPLE-VECTOR, conflicting with its asserted type LIST.
;   See also:
;     The SBCL Manual, Node "Handling of Types"
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {100E4D0283}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "local-time" "src" "local-time">

```

*local-time/test* fails to build because of a failure in  _local-time_.

[Full log here](http://report.quicklisp.org/2021-01-03/failure-report/local-time.html)

**Comment by dlowe-net** [comment]
Not sure if this is still an issue, but I couldn't get this to fire on latest.
