### ISSUE TITLE
Add local-time:encode-universal-time?

### ISSUE THREAD

**Issue by kilianmh** [dlowe-net/local-time#120]
The function `cl:encode-universal-time` gives inconsistent results across different implementations due to different values for the `time-zone`. Do you think we'd add a function `local-time:encode-universal-time` to shadow the original while keeping the same function signature but `time-zone` set by default to `0`? I think this might be useful in other projects.

**Comment by dlowe-net** [comment]
Sorry, I don't think this is within the scope of the library.

**Comment by kilianmh** [comment]
I'm writing about this function:

```common-lisp
(defun encode-universal-time (second minute hour date month year &optional (time-zone 0))
  (cl:encode-universal-time second minute hour date month year time-zone))
```

The only difference is that time-zone defaults to 0.

Are you sure this is out of scope?
