### ISSUE TITLE
adjust-timestamp - fails to set day, month, year

### ISSUE THREAD

**Issue by mdbergmann** [dlowe-net/local-time#121]
Hi.

`adjust-timestamp` (also with `!`) fails to set the correct date.
I tried `:day`, `:month` and `:year` each individually or together as 3 times `set`.

For time it seems to work correctly, but not for date.

Test on SBCL 2.1.11, 2.3.4 and CCL 1.12.2.

```
#<PACKAGE "LOCAL-TIME">
LOCAL-TIME(3): (adjust-timestamp (today))
; in: ADJUST-TIMESTAMP (TODAY)
;     (#:NEW138 (LOCAL-TIME:CLONE-TIMESTAMP #:OLD137))
;

@2024-04-18T02:00:00.000000+02:00
LOCAL-TIME(4): (adjust-timestamp (today) (set :day 22))

@2000-03-23T01:00:00.000000+01:00
LOCAL-TIME(5): (adjust-timestamp (today) (set :hour 22))

@2024-04-18T22:00:00.000000+02:00
LOCAL-TIME(6):
```

**Comment by mdbergmann** [comment]
OK, apparently I used the wrong combination. Instead `:day` one has to use `:day-of-month`, otherwise you get the result as above.

**Comment by dlowe-net** [comment]
Yeah, sorry for that footgun.
