### ISSUE TITLE
clock-today returns erroneous values

### ISSUE THREAD

**Issue by inventor500** [dlowe-net/local-time#122]
The `clock-today` function returns midnight UTC for the day, but returns a value in the local timezone. For those of us in the western hemisphere, this value is on the wrong day. It would be nice if this returned either midnight in local time, or converted the timestamp to UTC time, instead of returning an incorrect day.

```lisp
; This example is in the America/Chicago (CDT) timezone.

(local-time:clock-now local-time:*clock*)
; @2024-04-20T06:11:16.204242-05:00
(local-time:clock-today local-time:*clock*)
; @2024-04-19T19:00:00.000000-05:00

(let ((time (local-time:clock-now local-time:*clock*)))
         (local-time:adjust-timestamp time
           (set :sec-of-day 0)
           (set :nsec 0)))
; @2024-04-19T19:00:00.000000-05:00

(let ((time (local-time:clock-now local-time:*clock*)))
         (setf (local-time:nsec-of time) 0)
         (setf (local-time:sec-of time) 0)
         time)
; @2024-04-19T19:00:00.000000-05:00
```

**Comment by mmontone** [comment]
Yes, `clock-today` doesn't work well for me either.

Something like this perhaps?: 

```
(let ((now (now)))
              (encode-timestamp 0 0 0 0 (timestamp-day now) 
                                (timestamp-month now)
                                (timestamp-year now)))
```

**Comment by dlowe-net** [comment]
The intent (for good or ill) is to provide a naive date object, not to provide a convenient way to get a timestamp at midnight. That can be done pretty easily with `adjust-timestamp`.

**Comment by inventor500** [comment]
I don't especially care whether the time is at midnight or not, but it currently returns the wrong date.

**Comment by dlowe-net** [comment]
```
LOCAL-TIME> (format-timestring nil (clock-now nil) :timezone +utc-zone+)
"2024-04-24T01:49:03.384774Z"
LOCAL-TIME> (format-timestring nil (clock-today nil) :timezone +utc-zone+)                         
"2024-04-24T00:00:00.000000Z"
```

Returned proper date at UTC.

**Comment by inventor500** [comment]
So this is only guaranteed to produce the correct date when using the UTC time zone?

**Comment by dlowe-net** [comment]
You're not meant to use it as a timestamp at all. If you don't have a use for a naive date, just ignore it.
