### ISSUE TITLE
regressions in quicklisp 2013-06-15

### ISSUE THREAD

**Issue by avodonosov** [dlowe-net/local-time#15]
[I've tried to send this report to the local-time-devel, but don't see the message delivered]

In quicklisp 2013-06-15 local time test suite started to fail on all the lisps.
Also, local time doesn't even load on ECL, thus breaking all the depended libraries.

Here is the cl-test-grid page of local-time:
http://common-lisp.net/project/cl-test-grid/library/local-time.html

The test status links, like "(WHOLE-TEST-SUITE FAIL)",
refer to the lisp process output where this test result was obtained.

**Comment by dlowe-net** [comment]
The CL test grid looks fine these days.
