### ISSUE TITLE
test regression: test.simple.test/adjust-timestamp/bug3

### ISSUE THREAD

**Issue by avodonosov** [dlowe-net/local-time#4]
Test regression on between between quicklisp 2012-07-03 and quicklisp 2012-05-20.
New failure is test.simple.test/adjust-timestamp/bug3.

failures on ccl-1.8-f95-linux-x86:
    quicklisp 2012-07-03: test.simple.test/adjust-timestamp/bug2 test.simple.test/adjust-timestamp/bug3 (log: http://cl-test-grid.appspot.com/blob?key=187096)
    quicklisp 2012-05-20: test.simple.test/adjust-timestamp/bug2 (log: http://cl-test-grid.appspot.com/blob?key=177044)

failures on cmu-20c_release-20c__20c_unicode_-linux-x86:
    quicklisp 2012-07-03: test.simple.test/adjust-timestamp/bug2 test.simple.test/adjust-timestamp/bug3 (log: http://cl-test-grid.appspot.com/blob?key=198057)
    quicklisp 2012-05-20: test.simple.test/adjust-timestamp/bug2  (log: http://cl-test-grid.appspot.com/blob?key=178062)

BTW, what is meant by "bug3", "bug2" in the names of the test cases?

**Comment by dlowe-net** [comment]
This issue is obsoleted.
