### ISSUE TITLE
parse-timestring is double

### ISSUE THREAD

**Issue by jiroukaja** [dlowe-net/local-time#42]
I'm sorry for only reporting. Is this behavior correct?
I assume that parse-timestring is double counting timezone's value.
```lisp
CL-USER> local-time:*default-timezone*
#<TIMEZONE JCST JDT JST>
CL-USER> (local-time:parse-timestring "2015-06-28T12:06:00")
@2015-06-28T21:06:00.000000+09:00
CL-USER> (local-time:now)
@2015-06-28T12:06:16.164191+09:00
```
Time: 2015-06-28T12:06:00+09:00:00(in Japan +09:00:00).
Lisp: Clozure Common Lisp Version 1.11-dev-r16435M-trunk  (DarwinX8664)
Version: quicklisp's local-time-20150608-git

**Comment by dlowe-net** [comment]
The function `parse-timestring` doesn't use `*default-timezone*`, since the function doesn't know the offset from UTC. Specifying the `:offset` parameter to `parse-timestring` or including the offset within the timestring will give you the result you want.

    CL-USER> local-time:*default-timezone*
    #<LOCAL-TIME::TIMEZONE CJT JDT JST>
    CL-USER> (local-time:parse-timestring "2015-06-28T12:06:00+09:00")
    @2015-06-28T12:06:00.000000+09:00
    CL-USER> (local-time:parse-timestring "2015-06-28T12:06:00" :offset (* 9 3600))
    @2015-06-28T12:06:00.000000+09:00

**Comment by jiroukaja** [comment]
Thank you for response.
I would like to use with :offset.
