### ISSUE TITLE
Question: how to convert a timestamp to another timezone?

### ISSUE THREAD

**Issue by mmontone** [dlowe-net/local-time#45]
Hello.

How can I convert a local-time:timestamp to another timezone? I have timestamps in GMT-3 that need to be converted to UTC.

Thanks!

**Comment by mmontone** [comment]
Nevermind. It seems the timezone is not in the timestamp object?

**Comment by dlowe-net** [comment]
That's right. You pick a timezone when you decode or format the timestamp.
