### ISSUE TITLE
Timezones handling

### ISSUE THREAD

**Issue by mmontone** [dlowe-net/local-time#47]
Hello,

I have a question regarding timestamps and timezones.

I'm not getting the numbers I expect when I do some time calculations.

I'm following this article on timezones handling: http://www.creativedeletion.com/2015/05/10/the-need-timezones.html

It shows this example:

```elixir
iex> at_four = DateTime.from_erl!({{2014,3,30},{4,00,00}}, "Europe/Stockholm")
iex> at_one =  DateTime.from_erl!({{2014,3,30},{1,00,00}}, "Europe/Stockholm")
iex> DateTime.diff(at_four, at_one)
{:ok, 7200, 0}
# 7200 seconds is two hours in this case
```

Now, if I try something similar with local-time, I get three hours, instead of 2, which I assume is incorrect:

```lisp
CL-USER> (defparameter *at-four* (local-time:encode-timestamp 0 0 0 4 30 3 2014 :timezone (local-time:find-timezone-by-location-name "Europe/Stockholm")))
*AT-FOUR*
CL-USER> (defparameter *at-one* (local-time:encode-timestamp 0 0 0 1 30 3 2014 :timezone (local-time:find-timezone-by-location-name "Europe/Stockholm")))
*AT-ONE*
CL-USER> *at-four*
@2014-03-30T04:00:00.000000+02:00
CL-USER> *at-one*
@2014-03-30T00:00:00.000000+01:00
CL-USER> (local-time:timestamp-difference *at-four* *at-one*)
10800
```

I've also tested this with Python libraries, and it also gives the correct answer (2 hours instead of 3).

Is this a bug? Is this something that is not supported by local-time library?

Sorry for bothering with this. I'm evaluating libraries and stuff because I'm developing a calendar application that turns out to be in Common Lisp and this kind of thing is important.

Thanks

**Comment by mmontone** [comment]
There's a patch here that may be worth adding: https://mailman.common-lisp.net/pipermail/local-time-devel/2015-December/000185.html

**Comment by dlowe-net** [comment]
local-time is correct here.
```
CL-USER> (defparameter *at-four* (local-time:encode-timestamp 0 0 0 4 30 3 2014 :timezone (local-time:find-timezone-by-location-name "Europe/Stockholm")))
*AT-FOUR*
CL-USER> (defparameter *at-one* (local-time:encode-timestamp 0 0 0 1 30 3 2014 :timezone (local-time:find-timezone-by-location-name "Europe/Stockholm")))
*AT-ONE*
CL-USER> (setf local-time:*default-timezone* local-time:+utc-zone+)
#<TIMEZONE UTC>
CL-USER> *at-four*
@2014-03-30T02:00:00.000000Z
CL-USER> *at-one*
@2014-03-29T23:00:00.000000Z
```

**Comment by mmontone** [comment]
The problem is in timestamp-difference. It should be 7200, but I get:

```
CL-USER> (local-time:timestamp-difference *at-four* *at-one*)
10800
```

**Comment by dlowe-net** [comment]
It should not be 7200. If you convert to UTC, as I did above, it's pretty obvious that the two times are three hours apart.

It's more likely that `encode-timestamp` is guessing at the time offset from UTC differently than your other tested libraries. If you want control over this, you'll need to specify it directly with the :offset keyword argument.

**Comment by mmontone** [comment]
Ok. Never mind. I thought there was an error because apparently the hours between those two days is 2, and not 3, because of DST. And I confirmed that with Python and Java libraries (and the Erlang blog post), and LOCAL-TIME returns something else (as if there were a problem with timezones and DST, at least in this particular case).

**Comment by mmontone** [comment]
I get:

```
LOCAL-TIME> (local-time:timestamp-difference *at-four* *at-one*)
7200
```
in current implementation. So the problem in this issue may be solved now.
