### ISSUE TITLE
Issue when loading zoneinfo from custom folder

### ISSUE THREAD

**Issue by diogoalexandrefranco** [dlowe-net/local-time#48]
Hi,

I'm trying to load the zoneinfo information from a folder other than the local-time system (this is relevant for our deployment process). I understand that reread-timezone-repository takes a timezone-repository argument for this. However, i hit the following error:

    (local-time:reread-timezone-repository :timezone-repository #P"/usr/share/zoneinfo/")

    Debugger received error of type: SIMPLE-TYPE-ERROR
    In function SUBSEQ, the value of the argument :START is
       20
    which is not of the expected type (INTEGER 0 ...)

This seems to be because at some point we call the *visitor* local-method with the file "/etc/localtime", but the cutoff-position is still the same (20). Any idea on how to fix this?

Many thanks for this awesome library by the way.

**Comment by dlowe-net** [comment]
Thanks for the report! This has been fixed in 662cedb410ecef60f2f6fe52bf305a48b75a2b9c. We just haven't pushed it out to Quicklisp yet.
