### ISSUE TITLE
error opening /etc/localtime if /etc/localtime is a bogus symlink

### ISSUE THREAD

**Issue by slyrus** [dlowe-net/local-time#63]
This probably isn't really a local-time bug, but I'm putting it here for discussion, and as a reminder, if others run across it. The problem is caused by the fact that some docker containers (e.g. ubuntu/latest) ship with an /etc/localtime file that is a broken symlink to a file that doesn't exist.

In local-time, we proble-file /etc/localtime, and then attempt to read it. Should we use uiop's probe-file*, which verifies that the symlink exists?

**Comment by dlowe-net** [comment]
I agree. This isn't great behavior, especially on loading. It's also not good for Windows users. It defaults to UTC if the probe-file fails, so that should be the behavior if any part of the loading fails. What do you think?

**Comment by slyrus** [comment]
I agree. Easy enough :)
