### ISSUE TITLE
Forcing timestamps in UTC

### ISSUE THREAD

**Issue by boechat107** [dlowe-net/local-time#70]
Am I doing something wrong here?

```cl
(let ((local-time:*default-timezone* local-time:+utc-zone+))
  (local-time:now))
;; => @2017-11-30T11:06:08.018148-02:00
```

`now` still gets my local timezone.

**Comment by dlowe-net** [comment]
Yes. Timestamps are timezone-agnostic, so setting the default timezone while calling `now` doesn't do anything. When the current timestamp is returned from the `let`, the REPL then prints out the result, which uses `*default-timezone*`.

This should do what you expect:
```common-lisp
(let ((local-time:*default-timezone* local-time:+utc-zone+))
  (format-timestamp nil (local-time:now)))
```

**Comment by boechat107** [comment]
Sure, I understood it after reading the code. I should have read it before creating the issue.

Great library, by the way!

Thank you
