### ISSUE TITLE
TIMESTAMP/= behaves differently than CL:/=

### ISSUE THREAD

**Issue by attila-lendvai** [dlowe-net/local-time#72]
currently it behaves differently than CL:/= in that CL:/= returns T iff none of pairs are equal. TIMESTAMP/= returns T if at least one pair is not equal.

i suggest either mimicing CL:/= or adding a note to the code and a unit test to document this behavior.

```
CL-USER> (local-time:timestamp/= (mapcar 'local-time:parse-timestring '("2000-01-01" "2000-01-02" "2000-01-01")))
T
CL-USER> (/= 1 2 1)
NIL
```

**Comment by dlowe-net** [comment]
Yeah, that's totally fair. This should be done.
