### ISSUE TITLE
SBCL: incorrect variable names

### ISSUE THREAD

**Issue by phoe** [dlowe-net/local-time#84]
https://github.com/dlowe-net/local-time/blob/dc54f61415c76ee755a6f69d4154a3a282f2789f/src/local-time.lisp#L1068

Via http://www.sbcl.org/manual/:
```
Function: get-time-of-day [sb-ext]
    Return the number of seconds and microseconds since the beginning of the unix epoch (January 1st 1970.) 
```

This function, according to the documentation, returns microseconds and not nanoseconds then - the variable name `nsec` is incorrect.

**Comment by jonatack** [comment]
True, microseconds are abbreviated to usec / μsec / μs.
```lisp
CL-USER> (sb-ext:get-time-of-day)
1561816323
461713
```

**Comment by jonatack** [comment]
Might need verifying elsewhere in the codebase and docs.

**Comment by dlowe-net** [comment]
You got it!
