### ISSUE TITLE
Comma isn't a valid rfc3339 fractional seconds separator

### ISSUE THREAD

**Issue by fisxoj** [dlowe-net/local-time#90]
I was using local-time in a project that has a test suite that spans many languages (json-schema) and local time is parsing time strings that are considered invalid by the test suite.  After looking at https://www.ietf.org/rfc/rfc3339.txt, it does seem like section 5.6 "Internet Date/Time Format" specifies that the separator between seconds and fractional seconds is only a period, but local-time allows commas as well.  It looks like that was valid in the ISO 8601 standard, but not rfc3339.

If you don't want to make the parser stricter, could it maybe be made optionally stricter with something like a keyword argument to `parse-timestring` or just making `parse-rfc3339-timestring` use the stricter parsing?

I could probably chip in if you don't have time but could advise me on an acceptable solution.

**Comment by dlowe-net** [comment]
Does the PR fix the problem?

**Comment by fisxoj** [comment]
That looks great to me!

Thank you for the library and for getting to this so quickly!
